# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.postgres.fields
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedChampion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('champion_id', models.IntegerField()),
                ('pick_turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('assisting_participant_ids', django.contrib.postgres.fields.ArrayField(size=None, base_field=models.IntegerField())),
                ('building_type', models.CharField(max_length=24)),
                ('creator_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=24)),
                ('item_after', models.IntegerField()),
                ('item_before', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('killer_id', models.IntegerField()),
                ('lane_type', models.CharField(max_length=16)),
                ('level_up_type', models.CharField(max_length=8)),
                ('monster_type', models.CharField(max_length=16)),
                ('participant_id', models.IntegerField()),
                ('skill_slot', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('tower_type', models.CharField(max_length=24)),
                ('victim_id', models.IntegerField()),
                ('ward_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('mastery_id', models.BigIntegerField()),
                ('rank', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('map_id', models.IntegerField()),
                ('match_creation', models.BigIntegerField()),
                ('match_duration', models.BigIntegerField()),
                ('match_id', models.BigIntegerField()),
                ('match_mode', models.CharField(max_length=16)),
                ('match_type', models.CharField(max_length=16)),
                ('match_version', models.CharField(max_length=16)),
                ('platform_id', models.CharField(max_length=8)),
                ('queue_type', models.CharField(max_length=24)),
                ('region', models.CharField(max_length=4)),
                ('season', models.CharField(max_length=24)),
            ],
            bases=(utils.mixins.IterableDataFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('champion_id', models.IntegerField()),
                ('highest_achieved_season_tier', models.CharField(blank=True, max_length=16, null=True)),
                ('participant_id', models.IntegerField()),
                ('spell1_id', models.IntegerField()),
                ('spell2_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('match_detail', models.ForeignKey(to='matches.MatchDetail')),
            ],
            bases=(utils.mixins.IterableDataFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParticipantFrame',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('current_gold', models.IntegerField()),
                ('jungle_minions_killed', models.IntegerField()),
                ('level', models.IntegerField()),
                ('minions_killed', models.IntegerField()),
                ('participant_id', models.IntegerField()),
                ('team_score', models.IntegerField()),
                ('total_gold', models.IntegerField()),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantIdentity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('participant_id', models.IntegerField()),
                ('match_detail', models.ForeignKey(to='matches.MatchDetail')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantStats',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('champ_level', models.IntegerField()),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('double_kills', models.IntegerField(blank=True, null=True)),
                ('first_blood_assist', models.BooleanField()),
                ('first_blood_kill', models.BooleanField()),
                ('first_inhibitor_assist', models.BooleanField()),
                ('first_inhibitor_kill', models.BooleanField()),
                ('first_tower_assist', models.BooleanField()),
                ('first_tower_kill', models.BooleanField()),
                ('gold_earned', models.IntegerField(blank=True, null=True)),
                ('gold_spent', models.IntegerField(blank=True, null=True)),
                ('inhibitor_kills', models.IntegerField(blank=True, null=True)),
                ('item0', models.IntegerField(blank=True, null=True)),
                ('item1', models.IntegerField(blank=True, null=True)),
                ('item2', models.IntegerField(blank=True, null=True)),
                ('item3', models.IntegerField(blank=True, null=True)),
                ('item4', models.IntegerField(blank=True, null=True)),
                ('item5', models.IntegerField(blank=True, null=True)),
                ('item6', models.IntegerField(blank=True, null=True)),
                ('killing_sprees', models.IntegerField(blank=True, null=True)),
                ('kills', models.IntegerField(blank=True, null=True)),
                ('largest_critical_strike', models.IntegerField(blank=True, null=True)),
                ('largest_killing_spree', models.IntegerField(blank=True, null=True)),
                ('largest_multi_kill', models.IntegerField(blank=True, null=True)),
                ('magic_damage_dealt', models.IntegerField(blank=True, null=True)),
                ('magic_damage_dealt_to_champions', models.IntegerField(blank=True, null=True)),
                ('magic_damage_taken', models.IntegerField(blank=True, null=True)),
                ('minions_killed', models.IntegerField(blank=True, null=True)),
                ('neutral_minions_killed', models.IntegerField(blank=True, null=True)),
                ('neutral_minions_killed_enemy_jungle', models.IntegerField(blank=True, null=True)),
                ('neutral_minions_killed_team_jungle', models.IntegerField(blank=True, null=True)),
                ('penta_kills', models.IntegerField(blank=True, null=True)),
                ('physical_damage_dealt', models.IntegerField(blank=True, null=True)),
                ('physical_damage_dealt_to_champions', models.IntegerField(blank=True, null=True)),
                ('physical_damage_taken', models.IntegerField(blank=True, null=True)),
                ('quadra_kills', models.IntegerField(blank=True, null=True)),
                ('sight_wards_bought_in_game', models.IntegerField(blank=True, null=True)),
                ('total_damage_dealt', models.IntegerField(blank=True, null=True)),
                ('total_damage_dealt_to_champions', models.IntegerField(blank=True, null=True)),
                ('total_damage_taken', models.IntegerField(blank=True, null=True)),
                ('total_heal', models.IntegerField(blank=True, null=True)),
                ('total_time_crowd_control_dealt', models.IntegerField(blank=True, null=True)),
                ('total_units_healed', models.IntegerField(blank=True, null=True)),
                ('tower_kills', models.IntegerField(blank=True, null=True)),
                ('triple_kills', models.IntegerField(blank=True, null=True)),
                ('true_damage_dealt', models.IntegerField(blank=True, null=True)),
                ('true_damage_dealt_to_champions', models.IntegerField(blank=True, null=True)),
                ('true_damage_taken', models.IntegerField(blank=True, null=True)),
                ('unreal_kills', models.IntegerField(blank=True, null=True)),
                ('vision_wards_bought_in_game', models.IntegerField(blank=True, null=True)),
                ('wards_killed', models.IntegerField(blank=True, null=True)),
                ('wards_placed', models.IntegerField(blank=True, null=True)),
                ('winner', models.BooleanField()),
                ('participant', models.OneToOneField(to='matches.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTimeline',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('lane', models.CharField(max_length=8)),
                ('role', models.CharField(max_length=16)),
                ('participant', models.OneToOneField(to='matches.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('match_history_uri', models.CharField(max_length=64)),
                ('profile_icon', models.IntegerField()),
                ('summoner_id', models.IntegerField()),
                ('summoner_name', models.CharField(max_length=24)),
                ('participant_identity', models.OneToOneField(to='matches.ParticipantIdentity')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('rank', models.IntegerField()),
                ('rune_id', models.IntegerField()),
                ('participant', models.ForeignKey(to='matches.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('baron_kills', models.IntegerField(blank=True, null=True)),
                ('dragon_kills', models.IntegerField(blank=True, null=True)),
                ('first_baron', models.BooleanField()),
                ('first_blood', models.BooleanField()),
                ('first_dragon', models.BooleanField()),
                ('first_inhibitor', models.BooleanField()),
                ('first_tower', models.BooleanField()),
                ('inhibitor_kills', models.IntegerField(blank=True, null=True)),
                ('team_id', models.IntegerField()),
                ('tower_kills', models.IntegerField(blank=True, null=True)),
                ('winner', models.BooleanField()),
                ('match_detail', models.ForeignKey(to='matches.MatchDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('frame_interval', models.BigIntegerField()),
                ('match_detail', models.OneToOneField(to='matches.MatchDetail')),
            ],
        ),
        migrations.AddField(
            model_name='participantframe',
            name='position',
            field=models.OneToOneField(to='matches.Position'),
        ),
        migrations.AddField(
            model_name='mastery',
            name='participant',
            field=models.ForeignKey(to='matches.Participant'),
        ),
        migrations.AddField(
            model_name='frame',
            name='timeline',
            field=models.ForeignKey(to='matches.Timeline'),
        ),
        migrations.AddField(
            model_name='event',
            name='frame',
            field=models.ForeignKey(to='matches.Frame'),
        ),
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.OneToOneField(to='matches.Position'),
        ),
        migrations.AddField(
            model_name='bannedchampion',
            name='team',
            field=models.ForeignKey(to='matches.Team'),
        ),
    ]
