from django.test import TestCase

from summoners.models import Summoner
from .models import MatchDetail

class TestMatchModels(TestCase):
    """
    Parent class for matches models tests that creates all the instances
    required to represent the entirety of a match.

    Since models that contain FKs pointing to parent instances' create_
    methods do not touch said FKs, we require parent instances to exist
    so we can use _set managers to create the associated child instances.

    ex.
    team = self.match.team_set.get(team_id=100)
    team.bannedchampion_set.all().delete()
    team.bannedchampion_set.create_banned_champion(ban_data)

    Note: Since setUp runs a lot of stuff that isn't being immediately tested
    it can make for misleading test coverage figures; ensure inheriting
    test cases provide appropriate coverage.
    """
    def setUp(self):
        self.match_data = \
            {'mapId': 11,
             'matchCreation': 1432253725073,
             'matchDuration': 1867,
             'matchId': 1831067977,
             'matchMode': 'CLASSIC',
             'matchType': 'MATCHED_GAME',
             'matchVersion': '5.9.0.318',
             'participantIdentities': [{'participantId': 1,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA1/216100119',
                                            'profileIcon': 1,
                                            'summonerId': 53434501,
                                            'summonerName': 'LaughingStapler'}},
                                       {'participantId': 2,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA/40738378',
                                            'profileIcon': 657,
                                            'summonerId': 26055342,
                                            'summonerName': 'PleaseDontBann'}},
                                       {'participantId': 3,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA1/215880437',
                                            'profileIcon': 6,
                                            'summonerId': 53106253,
                                            'summonerName': 'cactusbanana'}},
                                       {'participantId': 4,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA1/206407943',
                                            'profileIcon': 752,
                                            'summonerId': 43853345,
                                            'summonerName': 'ISIDEARMI'}},
                                       {'participantId': 5,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA/326712',
                                            'profileIcon': 580,
                                            'summonerId': 299878,
                                            'summonerName': 'Ronfar'}},
                                       {'participantId': 6,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA1/50462392',
                                            'profileIcon': 7,
                                            'summonerId': 35768227,
                                            'summonerName': 'smellerby14'}},
                                       {'participantId': 7,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA/35195198',
                                            'profileIcon': 28,
                                            'summonerId': 21699840,
                                            'summonerName': 'Evilxw'}},
                                       {'participantId': 8,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA/39584133',
                                            'profileIcon': 691,
                                            'summonerId': 25063569,
                                            'summonerName': 'FBG Hoe'}},
                                       {'participantId': 9,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA1/203896113',
                                            'profileIcon': 745,
                                            'summonerId': 40951562,
                                            'summonerName': 'TqashPKM'}},
                                       {'participantId': 10,
                                        'player': {
                                            'matchHistoryUri': '/v1/stats/player_history/NA1/203417104',
                                            'profileIcon': 786,
                                            'summonerId': 40299020,
                                            'summonerName': 'alexshlomo'}}],
             'participants': [{'championId': 154,
                               'highestAchievedSeasonTier': 'GOLD',
                               'masteries': [{'masteryId': 4111, 'rank': 1},
                                             {'masteryId': 4113, 'rank': 4},
                                             {'masteryId': 4123, 'rank': 3},
                                             {'masteryId': 4131, 'rank': 1},
                                             {'masteryId': 4133, 'rank': 1},
                                             {'masteryId': 4134, 'rank': 3},
                                             {'masteryId': 4143, 'rank': 3},
                                             {'masteryId': 4152, 'rank': 3},
                                             {'masteryId': 4154, 'rank': 1},
                                             {'masteryId': 4162, 'rank': 1},
                                             {'masteryId': 4211, 'rank': 2},
                                             {'masteryId': 4214, 'rank': 2},
                                             {'masteryId': 4221, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 3},
                                             {'masteryId': 4232, 'rank': 1}],
                               'participantId': 1,
                               'runes': [{'rank': 9, 'runeId': 5273},
                                         {'rank': 9, 'runeId': 5297},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 3, 'runeId': 5357}],
                               'spell1Id': 11,
                               'spell2Id': 4,
                               'stats': {'assists': 6,
                                         'champLevel': 13,
                                         'combatPlayerScore': 0,
                                         'deaths': 10,
                                         'doubleKills': 1,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': False,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 8837,
                                         'goldSpent': 8640,
                                         'inhibitorKills': 0,
                                         'item0': 3708,
                                         'item1': 3255,
                                         'item2': 3285,
                                         'item3': 1026,
                                         'item4': 3070,
                                         'item5': 0,
                                         'item6': 3340,
                                         'killingSprees': 1,
                                         'kills': 5,
                                         'largestCriticalStrike': 0,
                                         'largestKillingSpree': 2,
                                         'largestMultiKill': 2,
                                         'magicDamageDealt': 79002,
                                         'magicDamageDealtToChampions': 12765,
                                         'magicDamageTaken': 8846,
                                         'minionsKilled': 29,
                                         'neutralMinionsKilled': 48,
                                         'neutralMinionsKilledEnemyJungle': 0,
                                         'neutralMinionsKilledTeamJungle': 48,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 11064,
                                         'physicalDamageDealtToChampions': 312,
                                         'physicalDamageTaken': 18200,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 97428,
                                         'totalDamageDealtToChampions': 13510,
                                         'totalDamageTaken': 27951,
                                         'totalHeal': 11463,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 556,
                                         'totalUnitsHealed': 1,
                                         'towerKills': 0,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 7362,
                                         'trueDamageDealtToChampions': 432,
                                         'trueDamageTaken': 904,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 1,
                                         'wardsKilled': 2,
                                         'wardsPlaced': 7,
                                         'winner': False},
                               'teamId': 100,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 1.0,
                                                                   'twentyToThirty': 1.6,
                                                                   'zeroToTen': 0.2},
                                            'csDiffPerMinDeltas': {'tenToTwenty': 0.10000000000000006,
                                                                   'twentyToThirty': 0.7,
                                                                   'zeroToTen': 0.0},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': -343.49999999999994,
                                                'twentyToThirty': -132.0,
                                                'zeroToTen': -352.09999999999997},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 797.4000000000001,
                                                                        'twentyToThirty': 1284.0,
                                                                        'zeroToTen': 567.1},
                                            'goldPerMinDeltas': {'tenToTwenty': 292.9,
                                                                 'twentyToThirty': 323.5,
                                                                 'zeroToTen': 187.7},
                                            'lane': 'JUNGLE',
                                            'role': 'NONE',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': -20.799999999999983,
                                                                   'twentyToThirty': -123.89999999999998,
                                                                   'zeroToTen': -41.699999999999974},
                                            'xpPerMinDeltas': {'tenToTwenty': 390.6,
                                                               'twentyToThirty': 372.2,
                                                               'zeroToTen': 250.7}}},
                              {'championId': 31,
                               'highestAchievedSeasonTier': 'SILVER',
                               'masteries': [{'masteryId': 4113, 'rank': 4},
                                             {'masteryId': 4121, 'rank': 1},
                                             {'masteryId': 4123, 'rank': 3},
                                             {'masteryId': 4131, 'rank': 1},
                                             {'masteryId': 4133, 'rank': 1},
                                             {'masteryId': 4134, 'rank': 3},
                                             {'masteryId': 4143, 'rank': 3},
                                             {'masteryId': 4144, 'rank': 1},
                                             {'masteryId': 4152, 'rank': 3},
                                             {'masteryId': 4154, 'rank': 1},
                                             {'masteryId': 4162, 'rank': 1},
                                             {'masteryId': 4211, 'rank': 1},
                                             {'masteryId': 4212, 'rank': 2},
                                             {'masteryId': 4213, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 3},
                                             {'masteryId': 4312, 'rank': 1}],
                               'participantId': 2,
                               'runes': [{'rank': 9, 'runeId': 5273},
                                         {'rank': 9, 'runeId': 5297},
                                         {'rank': 9, 'runeId': 5327},
                                         {'rank': 3, 'runeId': 5357}],
                               'spell1Id': 14,
                               'spell2Id': 4,
                               'stats': {'assists': 7,
                                         'champLevel': 14,
                                         'combatPlayerScore': 0,
                                         'deaths': 9,
                                         'doubleKills': 0,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': False,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 10029,
                                         'goldSpent': 9920,
                                         'inhibitorKills': 0,
                                         'item0': 3027,
                                         'item1': 3020,
                                         'item2': 3001,
                                         'item3': 3089,
                                         'item4': 0,
                                         'item5': 0,
                                         'item6': 3340,
                                         'killingSprees': 1,
                                         'kills': 5,
                                         'largestCriticalStrike': 0,
                                         'largestKillingSpree': 2,
                                         'largestMultiKill': 1,
                                         'magicDamageDealt': 93598,
                                         'magicDamageDealtToChampions': 14419,
                                         'magicDamageTaken': 13795,
                                         'minionsKilled': 143,
                                         'neutralMinionsKilled': 11,
                                         'neutralMinionsKilledEnemyJungle': 4,
                                         'neutralMinionsKilledTeamJungle': 7,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 11593,
                                         'physicalDamageDealtToChampions': 907,
                                         'physicalDamageTaken': 16717,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 118626,
                                         'totalDamageDealtToChampions': 19800,
                                         'totalDamageTaken': 32110,
                                         'totalHeal': 5012,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 402,
                                         'totalUnitsHealed': 1,
                                         'towerKills': 1,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 13435,
                                         'trueDamageDealtToChampions': 4474,
                                         'trueDamageTaken': 1598,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 0,
                                         'wardsKilled': 0,
                                         'wardsPlaced': 4,
                                         'winner': False},
                               'teamId': 100,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 4.8,
                                                                   'twentyToThirty': 3.8,
                                                                   'zeroToTen': 5.0},
                                            'csDiffPerMinDeltas': {'tenToTwenty': -2.3999999999999995,
                                                                   'twentyToThirty': -4.440892098500626e-16,
                                                                   'zeroToTen': -1.2000000000000002},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': 617.0999999999999,
                                                'twentyToThirty': 878.7,
                                                'zeroToTen': 234.4},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 969.0,
                                                                        'twentyToThirty': 1410.6,
                                                                        'zeroToTen': 507.9},
                                            'goldPerMinDeltas': {'tenToTwenty': 325.79999999999995,
                                                                 'twentyToThirty': 400.4,
                                                                 'zeroToTen': 187.39999999999998},
                                            'lane': 'MIDDLE',
                                            'role': 'SOLO',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': -157.60000000000005,
                                                                   'twentyToThirty': 16.5,
                                                                   'zeroToTen': -24.599999999999994},
                                            'xpPerMinDeltas': {'tenToTwenty': 400.29999999999995,
                                                               'twentyToThirty': 461.8,
                                                               'zeroToTen': 409.6}}},
                              {'championId': 16,
                               'highestAchievedSeasonTier': 'UNRANKED',
                               'masteries': [{'masteryId': 4113, 'rank': 4},
                                             {'masteryId': 4121, 'rank': 1},
                                             {'masteryId': 4123, 'rank': 3},
                                             {'masteryId': 4133, 'rank': 1},
                                             {'masteryId': 4312, 'rank': 3},
                                             {'masteryId': 4313, 'rank': 3},
                                             {'masteryId': 4314, 'rank': 1},
                                             {'masteryId': 4322, 'rank': 3},
                                             {'masteryId': 4324, 'rank': 1},
                                             {'masteryId': 4331, 'rank': 3},
                                             {'masteryId': 4334, 'rank': 1},
                                             {'masteryId': 4342, 'rank': 1},
                                             {'masteryId': 4352, 'rank': 1},
                                             {'masteryId': 4353, 'rank': 3},
                                             {'masteryId': 4362, 'rank': 1}],
                               'participantId': 3,
                               'runes': [{'rank': 9, 'runeId': 5267},
                                         {'rank': 9, 'runeId': 5297},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 3, 'runeId': 5357}],
                               'spell1Id': 3,
                               'spell2Id': 4,
                               'stats': {'assists': 11,
                                         'champLevel': 13,
                                         'combatPlayerScore': 0,
                                         'deaths': 4,
                                         'doubleKills': 0,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': False,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 6726,
                                         'goldSpent': 5960,
                                         'inhibitorKills': 0,
                                         'item0': 3271,
                                         'item1': 2010,
                                         'item2': 1028,
                                         'item3': 2049,
                                         'item4': 0,
                                         'item5': 3069,
                                         'item6': 3362,
                                         'killingSprees': 0,
                                         'kills': 0,
                                         'largestCriticalStrike': 369,
                                         'largestKillingSpree': 0,
                                         'largestMultiKill': 0,
                                         'magicDamageDealt': 18040,
                                         'magicDamageDealtToChampions': 9775,
                                         'magicDamageTaken': 6746,
                                         'minionsKilled': 4,
                                         'neutralMinionsKilled': 0,
                                         'neutralMinionsKilledEnemyJungle': 0,
                                         'neutralMinionsKilledTeamJungle': 0,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 1068,
                                         'physicalDamageDealtToChampions': 367,
                                         'physicalDamageTaken': 5961,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 19108,
                                         'totalDamageDealtToChampions': 10143,
                                         'totalDamageTaken': 13567,
                                         'totalHeal': 15364,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 150,
                                         'totalUnitsHealed': 5,
                                         'towerKills': 0,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 0,
                                         'trueDamageDealtToChampions': 0,
                                         'trueDamageTaken': 859,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 1,
                                         'wardsKilled': 1,
                                         'wardsPlaced': 22,
                                         'winner': False},
                               'teamId': 100,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 0.2,
                                                                   'twentyToThirty': 0.1,
                                                                   'zeroToTen': 0.1},
                                            'csDiffPerMinDeltas': {'tenToTwenty': -0.6999999999999995,
                                                                   'twentyToThirty': -1.3500000000000003,
                                                                   'zeroToTen': -0.25},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': -224.45000000000005,
                                                'twentyToThirty': -257.6,
                                                'zeroToTen': -78.80000000000001},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 469.9,
                                                                        'twentyToThirty': 597.4,
                                                                        'zeroToTen': 70.4},
                                            'goldPerMinDeltas': {'tenToTwenty': 185.5,
                                                                 'twentyToThirty': 275.4,
                                                                 'zeroToTen': 122.1},
                                            'lane': 'BOTTOM',
                                            'role': 'DUO_SUPPORT',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': -111.80000000000001,
                                                                   'twentyToThirty': 14.750000000000057,
                                                                   'zeroToTen': -20.150000000000034},
                                            'xpPerMinDeltas': {'tenToTwenty': 249.6,
                                                               'twentyToThirty': 456.1,
                                                               'zeroToTen': 262.29999999999995}}},
                              {'championId': 222,
                               'highestAchievedSeasonTier': 'SILVER',
                               'masteries': [{'masteryId': 4112, 'rank': 4},
                                             {'masteryId': 4114, 'rank': 1},
                                             {'masteryId': 4122, 'rank': 3},
                                             {'masteryId': 4124, 'rank': 1},
                                             {'masteryId': 4134, 'rank': 3},
                                             {'masteryId': 4142, 'rank': 3},
                                             {'masteryId': 4144, 'rank': 1},
                                             {'masteryId': 4151, 'rank': 1},
                                             {'masteryId': 4152, 'rank': 3},
                                             {'masteryId': 4162, 'rank': 1},
                                             {'masteryId': 4211, 'rank': 2},
                                             {'masteryId': 4212, 'rank': 2},
                                             {'masteryId': 4221, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 3},
                                             {'masteryId': 4232, 'rank': 1}],
                               'participantId': 4,
                               'runes': [{'rank': 6, 'runeId': 5245},
                                         {'rank': 3, 'runeId': 5247},
                                         {'rank': 9, 'runeId': 5289},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 1, 'runeId': 5335},
                                         {'rank': 2, 'runeId': 5337}],
                               'spell1Id': 7,
                               'spell2Id': 4,
                               'stats': {'assists': 4,
                                         'champLevel': 13,
                                         'combatPlayerScore': 0,
                                         'deaths': 6,
                                         'doubleKills': 1,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': False,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 9542,
                                         'goldSpent': 9265,
                                         'inhibitorKills': 0,
                                         'item0': 3031,
                                         'item1': 3250,
                                         'item2': 3046,
                                         'item3': 1055,
                                         'item4': 1036,
                                         'item5': 0,
                                         'item6': 3363,
                                         'killingSprees': 1,
                                         'kills': 4,
                                         'largestCriticalStrike': 520,
                                         'largestKillingSpree': 3,
                                         'largestMultiKill': 2,
                                         'magicDamageDealt': 1265,
                                         'magicDamageDealtToChampions': 246,
                                         'magicDamageTaken': 8837,
                                         'minionsKilled': 157,
                                         'neutralMinionsKilled': 5,
                                         'neutralMinionsKilledEnemyJungle': 0,
                                         'neutralMinionsKilledTeamJungle': 5,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 109016,
                                         'physicalDamageDealtToChampions': 12593,
                                         'physicalDamageTaken': 9131,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 110589,
                                         'totalDamageDealtToChampions': 13014,
                                         'totalDamageTaken': 18327,
                                         'totalHeal': 1534,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 121,
                                         'totalUnitsHealed': 4,
                                         'towerKills': 0,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 308,
                                         'trueDamageDealtToChampions': 174,
                                         'trueDamageTaken': 358,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 0,
                                         'wardsKilled': 1,
                                         'wardsPlaced': 7,
                                         'winner': False},
                               'teamId': 100,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 5.5,
                                                                   'twentyToThirty': 4.9,
                                                                   'zeroToTen': 5.300000000000001},
                                            'csDiffPerMinDeltas': {'tenToTwenty': -0.6999999999999995,
                                                                   'twentyToThirty': -1.3500000000000003,
                                                                   'zeroToTen': -0.25},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': -224.45000000000005,
                                                'twentyToThirty': -257.6,
                                                'zeroToTen': -78.80000000000001},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 372.59999999999997,
                                                                        'twentyToThirty': 993.0,
                                                                        'zeroToTen': 276.40000000000003},
                                            'goldPerMinDeltas': {'tenToTwenty': 280.9,
                                                                 'twentyToThirty': 369.4,
                                                                 'zeroToTen': 201.2},
                                            'lane': 'BOTTOM',
                                            'role': 'DUO_CARRY',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': -111.80000000000001,
                                                                   'twentyToThirty': 14.750000000000057,
                                                                   'zeroToTen': -20.150000000000034},
                                            'xpPerMinDeltas': {'tenToTwenty': 338.1,
                                                               'twentyToThirty': 472.8,
                                                               'zeroToTen': 262.29999999999995}}},
                              {'championId': 102,
                               'highestAchievedSeasonTier': 'GOLD',
                               'masteries': [{'masteryId': 4112, 'rank': 4},
                                             {'masteryId': 4114, 'rank': 1},
                                             {'masteryId': 4122, 'rank': 3},
                                             {'masteryId': 4132, 'rank': 1},
                                             {'masteryId': 4211, 'rank': 2},
                                             {'masteryId': 4212, 'rank': 2},
                                             {'masteryId': 4213, 'rank': 2},
                                             {'masteryId': 4221, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 3},
                                             {'masteryId': 4232, 'rank': 1},
                                             {'masteryId': 4234, 'rank': 3},
                                             {'masteryId': 4241, 'rank': 1},
                                             {'masteryId': 4242, 'rank': 1},
                                             {'masteryId': 4252, 'rank': 4},
                                             {'masteryId': 4262, 'rank': 1}],
                               'participantId': 5,
                               'runes': [{'rank': 9, 'runeId': 5295},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 3, 'runeId': 5365},
                                         {'rank': 9, 'runeId': 5402}],
                               'spell1Id': 4,
                               'spell2Id': 12,
                               'stats': {'assists': 6,
                                         'champLevel': 16,
                                         'combatPlayerScore': 0,
                                         'deaths': 5,
                                         'doubleKills': 0,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': False,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 10500,
                                         'goldSpent': 9360,
                                         'inhibitorKills': 0,
                                         'item0': 3065,
                                         'item1': 3153,
                                         'item2': 0,
                                         'item3': 3047,
                                         'item4': 3082,
                                         'item5': 1028,
                                         'item6': 3340,
                                         'killingSprees': 2,
                                         'kills': 5,
                                         'largestCriticalStrike': 0,
                                         'largestKillingSpree': 2,
                                         'largestMultiKill': 1,
                                         'magicDamageDealt': 84777,
                                         'magicDamageDealtToChampions': 9096,
                                         'magicDamageTaken': 6888,
                                         'minionsKilled': 186,
                                         'neutralMinionsKilled': 1,
                                         'neutralMinionsKilledEnemyJungle': 1,
                                         'neutralMinionsKilledTeamJungle': 0,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 48722,
                                         'physicalDamageDealtToChampions': 7316,
                                         'physicalDamageTaken': 19092,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 5,
                                         'totalDamageDealt': 133802,
                                         'totalDamageDealtToChampions': 16546,
                                         'totalDamageTaken': 28519,
                                         'totalHeal': 1455,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 189,
                                         'totalUnitsHealed': 1,
                                         'towerKills': 1,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 303,
                                         'trueDamageDealtToChampions': 134,
                                         'trueDamageTaken': 2538,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 1,
                                         'wardsKilled': 0,
                                         'wardsPlaced': 11,
                                         'winner': False},
                               'teamId': 100,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 6.5,
                                                                   'twentyToThirty': 7.0,
                                                                   'zeroToTen': 5.0},
                                            'csDiffPerMinDeltas': {'tenToTwenty': -1.8000000000000003,
                                                                   'twentyToThirty': 5.2,
                                                                   'zeroToTen': -2.0999999999999996},
                                            'damageTakenDiffPerMinDeltas': {'tenToTwenty': 173.3,
                                                                            'twentyToThirty': 56.10000000000002,
                                                                            'zeroToTen': 116.79999999999998},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 850.2,
                                                                        'twentyToThirty': 1241.7,
                                                                        'zeroToTen': 410.9},
                                            'goldPerMinDeltas': {'tenToTwenty': 369.20000000000005,
                                                                 'twentyToThirty': 373.9,
                                                                 'zeroToTen': 226.79999999999998},
                                            'lane': 'TOP',
                                            'role': 'SOLO',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': -56.30000000000001,
                                                                   'twentyToThirty': 162.79999999999998,
                                                                   'zeroToTen': 9.100000000000023},
                                            'xpPerMinDeltas': {'tenToTwenty': 489.2,
                                                               'twentyToThirty': 597.4,
                                                               'zeroToTen': 467.6}}},
                              {'championId': 99,
                               'highestAchievedSeasonTier': 'SILVER',
                               'masteries': [{'masteryId': 4113, 'rank': 4},
                                             {'masteryId': 4121, 'rank': 1},
                                             {'masteryId': 4123, 'rank': 3},
                                             {'masteryId': 4133, 'rank': 1},
                                             {'masteryId': 4134, 'rank': 3},
                                             {'masteryId': 4143, 'rank': 3},
                                             {'masteryId': 4144, 'rank': 1},
                                             {'masteryId': 4152, 'rank': 3},
                                             {'masteryId': 4154, 'rank': 1},
                                             {'masteryId': 4162, 'rank': 1},
                                             {'masteryId': 4312, 'rank': 1},
                                             {'masteryId': 4313, 'rank': 3},
                                             {'masteryId': 4322, 'rank': 3},
                                             {'masteryId': 4324, 'rank': 1},
                                             {'masteryId': 4334, 'rank': 1}],
                               'participantId': 6,
                               'runes': [{'rank': 9, 'runeId': 5273},
                                         {'rank': 6, 'runeId': 5297},
                                         {'rank': 3, 'runeId': 5298},
                                         {'rank': 9, 'runeId': 5331},
                                         {'rank': 2, 'runeId': 5357},
                                         {'rank': 1, 'runeId': 5358}],
                               'spell1Id': 4,
                               'spell2Id': 21,
                               'stats': {'assists': 12,
                                         'champLevel': 16,
                                         'combatPlayerScore': 0,
                                         'deaths': 3,
                                         'doubleKills': 3,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': True,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 13035,
                                         'goldSpent': 11673,
                                         'inhibitorKills': 0,
                                         'item0': 2041,
                                         'item1': 3174,
                                         'item2': 3255,
                                         'item3': 3285,
                                         'item4': 3089,
                                         'item5': 0,
                                         'item6': 3340,
                                         'killingSprees': 3,
                                         'kills': 14,
                                         'largestCriticalStrike': 0,
                                         'largestKillingSpree': 9,
                                         'largestMultiKill': 2,
                                         'magicDamageDealt': 113006,
                                         'magicDamageDealtToChampions': 29511,
                                         'magicDamageTaken': 7368,
                                         'minionsKilled': 178,
                                         'neutralMinionsKilled': 4,
                                         'neutralMinionsKilledEnemyJungle': 4,
                                         'neutralMinionsKilledTeamJungle': 0,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 25550,
                                         'physicalDamageDealtToChampions': 3994,
                                         'physicalDamageTaken': 4772,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 138587,
                                         'totalDamageDealtToChampions': 33535,
                                         'totalDamageTaken': 12427,
                                         'totalHeal': 1935,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 291,
                                         'totalUnitsHealed': 1,
                                         'towerKills': 0,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 30,
                                         'trueDamageDealtToChampions': 30,
                                         'trueDamageTaken': 286,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 2,
                                         'wardsKilled': 1,
                                         'wardsPlaced': 12,
                                         'winner': True},
                               'teamId': 200,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 7.199999999999999,
                                                                   'twentyToThirty': 3.8000000000000003,
                                                                   'zeroToTen': 6.2},
                                            'csDiffPerMinDeltas': {'tenToTwenty': 2.3999999999999995,
                                                                   'twentyToThirty': 4.440892098500626e-16,
                                                                   'zeroToTen': 1.2000000000000002},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': -617.0999999999999,
                                                'twentyToThirty': -878.7,
                                                'zeroToTen': -234.4},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 351.9,
                                                                        'twentyToThirty': 531.9,
                                                                        'zeroToTen': 273.5},
                                            'goldPerMinDeltas': {'tenToTwenty': 447.3,
                                                                 'twentyToThirty': 485.4,
                                                                 'zeroToTen': 212.5},
                                            'lane': 'MIDDLE',
                                            'role': 'SOLO',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': 157.60000000000005,
                                                                   'twentyToThirty': -16.5,
                                                                   'zeroToTen': 24.599999999999994},
                                            'xpPerMinDeltas': {'tenToTwenty': 557.9000000000001,
                                                               'twentyToThirty': 445.3,
                                                               'zeroToTen': 434.2}}},
                              {'championId': 67,
                               'highestAchievedSeasonTier': 'SILVER',
                               'masteries': [{'masteryId': 4112, 'rank': 4},
                                             {'masteryId': 4114, 'rank': 1},
                                             {'masteryId': 4122, 'rank': 3},
                                             {'masteryId': 4124, 'rank': 1},
                                             {'masteryId': 4131, 'rank': 1},
                                             {'masteryId': 4132, 'rank': 1},
                                             {'masteryId': 4134, 'rank': 3},
                                             {'masteryId': 4141, 'rank': 1},
                                             {'masteryId': 4142, 'rank': 3},
                                             {'masteryId': 4144, 'rank': 1},
                                             {'masteryId': 4151, 'rank': 1},
                                             {'masteryId': 4162, 'rank': 1},
                                             {'masteryId': 4211, 'rank': 2},
                                             {'masteryId': 4212, 'rank': 2},
                                             {'masteryId': 4221, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 3},
                                             {'masteryId': 4232, 'rank': 1}],
                               'participantId': 7,
                               'runes': [{'rank': 8, 'runeId': 5245},
                                         {'rank': 1, 'runeId': 5251},
                                         {'rank': 3, 'runeId': 5277},
                                         {'rank': 6, 'runeId': 5289},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 3, 'runeId': 5337}],
                               'spell1Id': 4,
                               'spell2Id': 7,
                               'stats': {'assists': 8,
                                         'champLevel': 15,
                                         'combatPlayerScore': 0,
                                         'deaths': 3,
                                         'doubleKills': 1,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': True,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 12013,
                                         'goldSpent': 9410,
                                         'inhibitorKills': 1,
                                         'item0': 3153,
                                         'item1': 2003,
                                         'item2': 1055,
                                         'item3': 3250,
                                         'item4': 3087,
                                         'item5': 1038,
                                         'item6': 3340,
                                         'killingSprees': 3,
                                         'kills': 9,
                                         'largestCriticalStrike': 809,
                                         'largestKillingSpree': 3,
                                         'largestMultiKill': 2,
                                         'magicDamageDealt': 11177,
                                         'magicDamageDealtToChampions': 2000,
                                         'magicDamageTaken': 7766,
                                         'minionsKilled': 193,
                                         'neutralMinionsKilled': 5,
                                         'neutralMinionsKilledEnemyJungle': 2,
                                         'neutralMinionsKilledTeamJungle': 3,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 113409,
                                         'physicalDamageDealtToChampions': 14533,
                                         'physicalDamageTaken': 8446,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 139722,
                                         'totalDamageDealtToChampions': 22260,
                                         'totalDamageTaken': 18845,
                                         'totalHeal': 2903,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 77,
                                         'totalUnitsHealed': 3,
                                         'towerKills': 2,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 15134,
                                         'trueDamageDealtToChampions': 5725,
                                         'trueDamageTaken': 2633,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 0,
                                         'wardsKilled': 1,
                                         'wardsPlaced': 8,
                                         'winner': True},
                               'teamId': 200,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 6.699999999999999,
                                                                   'twentyToThirty': 7.2,
                                                                   'zeroToTen': 5.0},
                                            'csDiffPerMinDeltas': {'tenToTwenty': 0.6999999999999995,
                                                                   'twentyToThirty': 1.3500000000000003,
                                                                   'zeroToTen': 0.25},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': 224.45000000000005,
                                                'twentyToThirty': 257.6,
                                                'zeroToTen': 78.80000000000001},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 680.5,
                                                                        'twentyToThirty': 854.8,
                                                                        'zeroToTen': 271.7},
                                            'goldPerMinDeltas': {'tenToTwenty': 390.0,
                                                                 'twentyToThirty': 458.40000000000003,
                                                                 'zeroToTen': 194.2},
                                            'lane': 'BOTTOM',
                                            'role': 'DUO_CARRY',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': 111.80000000000001,
                                                                   'twentyToThirty': -14.750000000000057,
                                                                   'zeroToTen': 20.150000000000034},
                                            'xpPerMinDeltas': {'tenToTwenty': 447.6,
                                                               'twentyToThirty': 585.1,
                                                               'zeroToTen': 288.5}}},
                              {'championId': 19,
                               'highestAchievedSeasonTier': 'SILVER',
                               'masteries': [{'masteryId': 4112, 'rank': 4},
                                             {'masteryId': 4114, 'rank': 1},
                                             {'masteryId': 4121, 'rank': 1},
                                             {'masteryId': 4122, 'rank': 3},
                                             {'masteryId': 4124, 'rank': 1},
                                             {'masteryId': 4131, 'rank': 1},
                                             {'masteryId': 4132, 'rank': 1},
                                             {'masteryId': 4134, 'rank': 3},
                                             {'masteryId': 4141, 'rank': 1},
                                             {'masteryId': 4144, 'rank': 1},
                                             {'masteryId': 4152, 'rank': 3},
                                             {'masteryId': 4162, 'rank': 1},
                                             {'masteryId': 4211, 'rank': 2},
                                             {'masteryId': 4214, 'rank': 2},
                                             {'masteryId': 4221, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 3},
                                             {'masteryId': 4232, 'rank': 1}],
                               'participantId': 8,
                               'runes': [{'rank': 9, 'runeId': 5245},
                                         {'rank': 9, 'runeId': 5277},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 3, 'runeId': 5412}],
                               'spell1Id': 4,
                               'spell2Id': 11,
                               'stats': {'assists': 7,
                                         'champLevel': 15,
                                         'combatPlayerScore': 0,
                                         'deaths': 3,
                                         'doubleKills': 0,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': True,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 11194,
                                         'goldSpent': 10335,
                                         'inhibitorKills': 0,
                                         'item0': 3153,
                                         'item1': 3117,
                                         'item2': 3726,
                                         'item3': 3082,
                                         'item4': 3091,
                                         'item5': 1028,
                                         'item6': 3341,
                                         'killingSprees': 2,
                                         'kills': 6,
                                         'largestCriticalStrike': 0,
                                         'largestKillingSpree': 3,
                                         'largestMultiKill': 1,
                                         'magicDamageDealt': 54560,
                                         'magicDamageDealtToChampions': 4988,
                                         'magicDamageTaken': 9607,
                                         'minionsKilled': 25,
                                         'neutralMinionsKilled': 92,
                                         'neutralMinionsKilledEnemyJungle': 11,
                                         'neutralMinionsKilledTeamJungle': 81,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 84531,
                                         'physicalDamageDealtToChampions': 3610,
                                         'physicalDamageTaken': 27134,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 158479,
                                         'totalDamageDealtToChampions': 9102,
                                         'totalDamageTaken': 37080,
                                         'totalHeal': 16910,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 684,
                                         'totalUnitsHealed': 1,
                                         'towerKills': 0,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 19386,
                                         'trueDamageDealtToChampions': 503,
                                         'trueDamageTaken': 337,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 0,
                                         'wardsKilled': 8,
                                         'wardsPlaced': 0,
                                         'winner': True},
                               'teamId': 200,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 0.8999999999999999,
                                                                   'twentyToThirty': 0.9,
                                                                   'zeroToTen': 0.2},
                                            'csDiffPerMinDeltas': {'tenToTwenty': -0.10000000000000006,
                                                                   'twentyToThirty': -0.7,
                                                                   'zeroToTen': 0.0},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': 343.49999999999994,
                                                'twentyToThirty': 132.0,
                                                'zeroToTen': 352.09999999999997},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 1140.9,
                                                                        'twentyToThirty': 1416.0,
                                                                        'zeroToTen': 919.2},
                                            'goldPerMinDeltas': {'tenToTwenty': 385.1,
                                                                 'twentyToThirty': 388.8,
                                                                 'zeroToTen': 245.8},
                                            'lane': 'JUNGLE',
                                            'role': 'NONE',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': 20.799999999999983,
                                                                   'twentyToThirty': 123.89999999999998,
                                                                   'zeroToTen': 41.699999999999974},
                                            'xpPerMinDeltas': {'tenToTwenty': 411.4,
                                                               'twentyToThirty': 496.09999999999997,
                                                               'zeroToTen': 292.4}}},
                              {'championId': 89,
                               'highestAchievedSeasonTier': 'UNRANKED',
                               'masteries': [{'masteryId': 4211, 'rank': 2},
                                             {'masteryId': 4212, 'rank': 2},
                                             {'masteryId': 4213, 'rank': 2},
                                             {'masteryId': 4221, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 2},
                                             {'masteryId': 4312, 'rank': 3},
                                             {'masteryId': 4313, 'rank': 3},
                                             {'masteryId': 4323, 'rank': 1},
                                             {'masteryId': 4324, 'rank': 1},
                                             {'masteryId': 4331, 'rank': 3},
                                             {'masteryId': 4334, 'rank': 1},
                                             {'masteryId': 4341, 'rank': 1},
                                             {'masteryId': 4342, 'rank': 1},
                                             {'masteryId': 4343, 'rank': 3},
                                             {'masteryId': 4344, 'rank': 2},
                                             {'masteryId': 4352, 'rank': 1},
                                             {'masteryId': 4362, 'rank': 1}],
                               'participantId': 9,
                               'runes': [{'rank': 1, 'runeId': 5255},
                                         {'rank': 8, 'runeId': 5257},
                                         {'rank': 9, 'runeId': 5289},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 2, 'runeId': 5345},
                                         {'rank': 1, 'runeId': 5351}],
                               'spell1Id': 4,
                               'spell2Id': 3,
                               'stats': {'assists': 20,
                                         'champLevel': 13,
                                         'combatPlayerScore': 0,
                                         'deaths': 7,
                                         'doubleKills': 0,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': False,
                                         'firstInhibitorAssist': False,
                                         'firstInhibitorKill': True,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 8415,
                                         'goldSpent': 8200,
                                         'inhibitorKills': 1,
                                         'item0': 3111,
                                         'item1': 2049,
                                         'item2': 3401,
                                         'item3': 3065,
                                         'item4': 3751,
                                         'item5': 0,
                                         'item6': 3341,
                                         'killingSprees': 0,
                                         'kills': 1,
                                         'largestCriticalStrike': 0,
                                         'largestKillingSpree': 0,
                                         'largestMultiKill': 1,
                                         'magicDamageDealt': 9910,
                                         'magicDamageDealtToChampions': 5189,
                                         'magicDamageTaken': 10869,
                                         'minionsKilled': 18,
                                         'neutralMinionsKilled': 2,
                                         'neutralMinionsKilledEnemyJungle': 2,
                                         'neutralMinionsKilledTeamJungle': 0,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 6644,
                                         'physicalDamageDealtToChampions': 2909,
                                         'physicalDamageTaken': 10983,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 1,
                                         'totalDamageDealt': 17756,
                                         'totalDamageDealtToChampions': 8098,
                                         'totalDamageTaken': 23675,
                                         'totalHeal': 877,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 72,
                                         'totalUnitsHealed': 4,
                                         'towerKills': 0,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 1200,
                                         'trueDamageDealtToChampions': 0,
                                         'trueDamageTaken': 1822,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 0,
                                         'wardsKilled': 4,
                                         'wardsPlaced': 14,
                                         'winner': True},
                               'teamId': 200,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 0.4,
                                                                   'twentyToThirty': 0.5,
                                                                   'zeroToTen': 0.8999999999999999},
                                            'csDiffPerMinDeltas': {'tenToTwenty': 0.6999999999999995,
                                                                   'twentyToThirty': 1.3500000000000003,
                                                                   'zeroToTen': 0.25},
                                            'damageTakenDiffPerMinDeltas': {
                                                'tenToTwenty': 224.45000000000005,
                                                'twentyToThirty': 257.6,
                                                'zeroToTen': 78.80000000000001},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 610.9000000000001,
                                                                        'twentyToThirty': 1250.8,
                                                                        'zeroToTen': 232.70000000000002},
                                            'goldPerMinDeltas': {'tenToTwenty': 274.8,
                                                                 'twentyToThirty': 283.0,
                                                                 'zeroToTen': 124.1},
                                            'lane': 'BOTTOM',
                                            'role': 'DUO_SUPPORT',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': 111.80000000000001,
                                                                   'twentyToThirty': -14.750000000000057,
                                                                   'zeroToTen': 20.150000000000034},
                                            'xpPerMinDeltas': {'tenToTwenty': 363.7,
                                                               'twentyToThirty': 314.3,
                                                               'zeroToTen': 276.4}}},
                              {'championId': 150,
                               'highestAchievedSeasonTier': 'SILVER',
                               'masteries': [{'masteryId': 4111, 'rank': 1},
                                             {'masteryId': 4113, 'rank': 2},
                                             {'masteryId': 4114, 'rank': 1},
                                             {'masteryId': 4122, 'rank': 3},
                                             {'masteryId': 4124, 'rank': 1},
                                             {'masteryId': 4132, 'rank': 1},
                                             {'masteryId': 4211, 'rank': 2},
                                             {'masteryId': 4212, 'rank': 2},
                                             {'masteryId': 4221, 'rank': 1},
                                             {'masteryId': 4222, 'rank': 3},
                                             {'masteryId': 4232, 'rank': 1},
                                             {'masteryId': 4234, 'rank': 3},
                                             {'masteryId': 4241, 'rank': 3},
                                             {'masteryId': 4244, 'rank': 1},
                                             {'masteryId': 4252, 'rank': 4},
                                             {'masteryId': 4262, 'rank': 1}],
                               'participantId': 10,
                               'runes': [{'rank': 5, 'runeId': 5245},
                                         {'rank': 4, 'runeId': 5257},
                                         {'rank': 9, 'runeId': 5289},
                                         {'rank': 9, 'runeId': 5317},
                                         {'rank': 1, 'runeId': 5335},
                                         {'rank': 2, 'runeId': 5347}],
                               'spell1Id': 12,
                               'spell2Id': 4,
                               'stats': {'assists': 17,
                                         'champLevel': 16,
                                         'combatPlayerScore': 0,
                                         'deaths': 4,
                                         'doubleKills': 0,
                                         'firstBloodAssist': False,
                                         'firstBloodKill': True,
                                         'firstInhibitorAssist': True,
                                         'firstInhibitorKill': False,
                                         'firstTowerAssist': False,
                                         'firstTowerKill': False,
                                         'goldEarned': 11786,
                                         'goldSpent': 10545,
                                         'inhibitorKills': 0,
                                         'item0': 3153,
                                         'item1': 3111,
                                         'item2': 3068,
                                         'item3': 3022,
                                         'item4': 0,
                                         'item5': 0,
                                         'item6': 3340,
                                         'killingSprees': 1,
                                         'kills': 4,
                                         'largestCriticalStrike': 302,
                                         'largestKillingSpree': 2,
                                         'largestMultiKill': 1,
                                         'magicDamageDealt': 27923,
                                         'magicDamageDealtToChampions': 3425,
                                         'magicDamageTaken': 10692,
                                         'minionsKilled': 175,
                                         'neutralMinionsKilled': 17,
                                         'neutralMinionsKilledEnemyJungle': 5,
                                         'neutralMinionsKilledTeamJungle': 12,
                                         'objectivePlayerScore': 0,
                                         'pentaKills': 0,
                                         'physicalDamageDealt': 104960,
                                         'physicalDamageDealtToChampions': 16315,
                                         'physicalDamageTaken': 12811,
                                         'quadraKills': 0,
                                         'sightWardsBoughtInGame': 0,
                                         'totalDamageDealt': 132883,
                                         'totalDamageDealtToChampions': 19740,
                                         'totalDamageTaken': 23637,
                                         'totalHeal': 3132,
                                         'totalPlayerScore': 0,
                                         'totalScoreRank': 0,
                                         'totalTimeCrowdControlDealt': 736,
                                         'totalUnitsHealed': 1,
                                         'towerKills': 1,
                                         'tripleKills': 0,
                                         'trueDamageDealt': 0,
                                         'trueDamageDealtToChampions': 0,
                                         'trueDamageTaken': 134,
                                         'unrealKills': 0,
                                         'visionWardsBoughtInGame': 0,
                                         'wardsKilled': 0,
                                         'wardsPlaced': 7,
                                         'winner': True},
                               'teamId': 200,
                               'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 8.3,
                                                                   'twentyToThirty': 1.8,
                                                                   'zeroToTen': 7.1},
                                            'csDiffPerMinDeltas': {'tenToTwenty': 1.8000000000000003,
                                                                   'twentyToThirty': -5.2,
                                                                   'zeroToTen': 2.0999999999999996},
                                            'damageTakenDiffPerMinDeltas': {'tenToTwenty': -173.3,
                                                                            'twentyToThirty': -56.10000000000002,
                                                                            'zeroToTen': -116.79999999999998},
                                            'damageTakenPerMinDeltas': {'tenToTwenty': 676.9,
                                                                        'twentyToThirty': 1185.6,
                                                                        'zeroToTen': 294.1},
                                            'goldPerMinDeltas': {'tenToTwenty': 377.4,
                                                                 'twentyToThirty': 403.70000000000005,
                                                                 'zeroToTen': 269.3},
                                            'lane': 'TOP',
                                            'role': 'SOLO',
                                            'xpDiffPerMinDeltas': {'tenToTwenty': 56.30000000000001,
                                                                   'twentyToThirty': -162.79999999999998,
                                                                   'zeroToTen': -9.100000000000023},
                                            'xpPerMinDeltas': {'tenToTwenty': 545.5,
                                                               'twentyToThirty': 434.6,
                                                               'zeroToTen': 458.5}}}],
             'platformId': 'NA1',
             'queueType': 'RANKED_SOLO_5x5',
             'region': 'NA',
             'season': 'SEASON2015',
             'teams': [{'bans': [{'championId': 1, 'pickTurn': 1},
                                 {'championId': 8, 'pickTurn': 3},
                                 {'championId': 55, 'pickTurn': 5}],
                        'baronKills': 0,
                        'dominionVictoryScore': 0,
                        'dragonKills': 0,
                        'firstBaron': False,
                        'firstBlood': False,
                        'firstDragon': False,
                        'firstInhibitor': False,
                        'firstTower': False,
                        'inhibitorKills': 0,
                        'teamId': 100,
                        'towerKills': 4,
                        'vilemawKills': 0,
                        'winner': False},
                       {'bans': [{'championId': 79, 'pickTurn': 2},
                                 {'championId': 238, 'pickTurn': 4},
                                 {'championId': 7, 'pickTurn': 6}],
                        'baronKills': 0,
                        'dominionVictoryScore': 0,
                        'dragonKills': 4,
                        'firstBaron': False,
                        'firstBlood': True,
                        'firstDragon': True,
                        'firstInhibitor': True,
                        'firstTower': True,
                        'inhibitorKills': 2,
                        'teamId': 200,
                        'towerKills': 7,
                        'vilemawKills': 0,
                        'winner': True}]}

        self.match = MatchDetail.objects.create_match(self.match_data)

class MatchDetailTestCase(TestMatchModels):
    def test_create_when_match_new(self):
        """
        Ensure MatchDetail creation is successful when match is new.
        """
        all_matches = MatchDetail.objects.all()

        self.assertTrue(MatchDetail.objects.count() == 1)

        match = all_matches.get(match_id=1831067977)

        self.assertEqual(match.match_creation, 1432253725073)

    def test_create_when_match_exists(self):
        """
        Ensure MatchDetail doesn't create match when it already exists.
        """
        prev_match_count = MatchDetail.objects.count()
        MatchDetail.objects.create_match(self.match_data)
        curr_match_count = MatchDetail.objects.count()

        self.assertTrue(prev_match_count, curr_match_count)

    def test_match_date(self):
        expected_str = '2015-05-21 20:15:25.072999'

        self.assertEqual(str(self.match.match_date()), expected_str)

class BannedChampionTestCase(TestMatchModels):
    def test_create(self):
        """
        Ensure BannedChampion creation is successful.
        """
        ban_data = {'championId': 79, 'pickTurn': 2}
        team = self.match.team_set.get(team_id=100)
        team.bannedchampion_set.all().delete()

        self.assertFalse(team.bannedchampion_set.all().exists())

        team.bannedchampion_set.create_banned_champion(ban_data)
        created = team.bannedchampion_set.get(champion_id=79)

        self.assertEqual(created.pick_turn, 2)

class TeamTestCase(TestMatchModels):
    def test_create_without_bans(self):
        """
        Ensure Team creation is successful when there are no bans.
        """
        team_data = {'baronKills': 0,
                     'dominionVictoryScore': 0,
                     'dragonKills': 0,
                     'firstBaron': False,
                     'firstBlood': False,
                     'firstDragon': False,
                     'firstInhibitor': False,
                     'firstTower': False,
                     'inhibitorKills': 0,
                     'teamId': 100,
                     'towerKills': 4,
                     'vilemawKills': 0,
                     'winner': False}

        self.assertTrue(self.match.team_set.all().exists())

        self.match.team_set.all().delete()

        self.assertFalse(self.match.team_set.all().exists())

        self.match.team_set.create_team(team_data)
        created = self.match.team_set.get(team_id=100)

        self.assertEqual(created.tower_kills, 4)

    def test_color(self):
        """
        Ensure color() returns the correct strings.
        """
        blue_team = self.match.team_set.get(team_id=100)
        purple_team = self.match.team_set.get(team_id=200)

        self.assertEqual(blue_team.color(), 'Blue')
        self.assertEqual(purple_team.color(), 'Purple')

class ParticipantTest(TestMatchModels):
    def test_create_without_runes_and_masteries(self):
        """
        Ensure Participant creation is successful when there are no runes
        and masteries.
        """
        participant_data = {'championId': 154,
                            'highestAchievedSeasonTier': 'GOLD',
                            'participantId': 1,
                            'spell1Id': 11,
                            'spell2Id': 4,
                            'stats': {'assists': 6,
                                      'champLevel': 13,
                                      'combatPlayerScore': 0,
                                      'deaths': 10,
                                      'doubleKills': 1,
                                      'firstBloodAssist': False,
                                      'firstBloodKill': False,
                                      'firstInhibitorAssist': False,
                                      'firstInhibitorKill': False,
                                      'firstTowerAssist': False,
                                      'firstTowerKill': False,
                                      'goldEarned': 8837,
                                      'goldSpent': 8640,
                                      'inhibitorKills': 0,
                                      'item0': 3708,
                                      'item1': 3255,
                                      'item2': 3285,
                                      'item3': 1026,
                                      'item4': 3070,
                                      'item5': 0,
                                      'item6': 3340,
                                      'killingSprees': 1,
                                      'kills': 5,
                                      'largestCriticalStrike': 0,
                                      'largestKillingSpree': 2,
                                      'largestMultiKill': 2,
                                      'magicDamageDealt': 79002,
                                      'magicDamageDealtToChampions': 12765,
                                      'magicDamageTaken': 8846,
                                      'minionsKilled': 29,
                                      'neutralMinionsKilled': 48,
                                      'neutralMinionsKilledEnemyJungle': 0,
                                      'neutralMinionsKilledTeamJungle': 48,
                                      'objectivePlayerScore': 0,
                                      'pentaKills': 0,
                                      'physicalDamageDealt': 11064,
                                      'physicalDamageDealtToChampions': 312,
                                      'physicalDamageTaken': 18200,
                                      'quadraKills': 0,
                                      'sightWardsBoughtInGame': 0,
                                      'totalDamageDealt': 97428,
                                      'totalDamageDealtToChampions': 13510,
                                      'totalDamageTaken': 27951,
                                      'totalHeal': 11463,
                                      'totalPlayerScore': 0,
                                      'totalScoreRank': 0,
                                      'totalTimeCrowdControlDealt': 556,
                                      'totalUnitsHealed': 1,
                                      'towerKills': 0,
                                      'tripleKills': 0,
                                      'trueDamageDealt': 7362,
                                      'trueDamageDealtToChampions': 432,
                                      'trueDamageTaken': 904,
                                      'unrealKills': 0,
                                      'visionWardsBoughtInGame': 1,
                                      'wardsKilled': 2,
                                      'wardsPlaced': 7,
                                      'winner': False},
                            'teamId': 100,
                            'timeline': {'creepsPerMinDeltas': {'tenToTwenty': 1.0,
                                                                'twentyToThirty': 1.6,
                                                                'zeroToTen': 0.2},
                                         'csDiffPerMinDeltas': {'tenToTwenty': 0.10000000000000006,
                                                                'twentyToThirty': 0.7,
                                                                'zeroToTen': 0.0},
                                         'damageTakenDiffPerMinDeltas': {'tenToTwenty': -343.49999999999994,
                                                                         'twentyToThirty': -132.0,
                                                                         'zeroToTen': -352.09999999999997},
                                         'damageTakenPerMinDeltas': {'tenToTwenty': 797.4000000000001,
                                                                     'twentyToThirty': 1284.0,
                                                                     'zeroToTen': 567.1},
                                         'goldPerMinDeltas': {'tenToTwenty': 292.9,
                                                              'twentyToThirty': 323.5,
                                                              'zeroToTen': 187.7},
                                         'lane': 'JUNGLE',
                                         'role': 'NONE',
                                         'xpDiffPerMinDeltas': {'tenToTwenty': -20.799999999999983,
                                                                'twentyToThirty': -123.89999999999998,
                                                                'zeroToTen': -41.699999999999974},
                                         'xpPerMinDeltas': {'tenToTwenty': 390.6,
                                                            'twentyToThirty': 372.2,
                                                            'zeroToTen': 250.7}}}

        self.assertTrue(self.match.participant_set.all().exists())

        self.match.participant_set.all().delete()

        self.assertFalse(self.match.participant_set.all().exists())

        self.match.participant_set.create_participant(participant_data)
        created = self.match.participant_set.get(participant_id=1)

        self.assertEqual(created.champion_id, 154)

class ParticipantIdentityTest(TestMatchModels):
    def test_create(self):
        """
        Ensure ParticipantIdentity creation is successful.
        """
        participant_identity_data = {'participantId': 1,
                                     'player': {'matchHistoryUri': '/v1/stats/player_history/NA1/216100119',
                                                'profileIcon': 1,
                                                'summonerId': 53434501,
                                                'summonerName': 'LaughingStapler'}}

        self.assertTrue(self.match.participantidentity_set.all().exists())

        self.match.participantidentity_set.all().delete()

        self.assertFalse(self.match.participantidentity_set.all().exists())

        self.match.participantidentity_set.\
            create_participant_identity(participant_identity_data)
        created = self.match.participant_set.get(participant_id=1)

        self.assertEqual(created.match_detail, self.match)

    def test_summoner_association(self):
        """
        Ensure `summoner` FK points to correct Summoner instance.
        """
        participant_identity = self.match.participantidentity_set.get(
            participant_id=1)
        summoner = Summoner.objects.get(summoner_id=53434501)

        self.assertEqual(participant_identity.summoner, summoner)

class MasteryTest(TestMatchModels):
    def test_create(self):
        """
        Ensure Mastery creation is successful.
        """
        mastery_data = {'masteryId': 4111, 'rank': 1}

        participant = self.match.participant_set.get(participant_id=1)

        self.assertTrue(participant.mastery_set.all().exists())

        participant.mastery_set.all().delete()

        self.assertFalse(participant.mastery_set.all().exists())

        participant.mastery_set.create_mastery(mastery_data)
        created = participant.mastery_set.get(mastery_id=4111)

        self.assertEqual(created.rank, 1)

class ParticipantTimelineTest(TestMatchModels):
    def test_create(self):
        """
        Ensure ParticipantTimeline creation is successful.
        """
        participant_timeline_data = {'creepsPerMinDeltas': {'tenToTwenty': 1.0,
                                                            'twentyToThirty': 1.6,
                                                            'zeroToTen': 0.2},
                                     'csDiffPerMinDeltas': {'tenToTwenty': 0.10000000000000006,
                                                            'twentyToThirty': 0.7,
                                                            'zeroToTen': 0.0},
                                     'damageTakenDiffPerMinDeltas': {'tenToTwenty': -343.49999999999994,
                                                                     'twentyToThirty': -132.0,
                                                                     'zeroToTen': -352.09999999999997},
                                     'damageTakenPerMinDeltas': {'tenToTwenty': 797.4000000000001,
                                                                 'twentyToThirty': 1284.0,
                                                                 'zeroToTen': 567.1},
                                     'goldPerMinDeltas': {'tenToTwenty': 292.9,
                                                          'twentyToThirty': 323.5,
                                                          'zeroToTen': 187.7},
                                     'lane': 'JUNGLE',
                                     'role': 'NONE',
                                     'xpDiffPerMinDeltas': {'tenToTwenty': -20.799999999999983,
                                                            'twentyToThirty': -123.89999999999998,
                                                            'zeroToTen': -41.699999999999974},
                                     'xpPerMinDeltas': {'tenToTwenty': 390.6,
                                                        'twentyToThirty': 372.2,
                                                        'zeroToTen': 250.7}}

        participant = self.match.participant_set.get(participant_id=1)

        self.assertTrue(participant.participanttimeline_set.all().exists())

        participant.participanttimeline_set.all().delete()

        self.assertFalse(participant.participanttimeline_set.all().exists())
        
        participant.participanttimeline_set.\
            create_participant_timeline(participant_timeline_data)
        created = participant.participanttimeline_set.get(lane='JUNGLE')

        self.assertEqual(created.role, 'NONE')

class RuneTest(TestMatchModels):
    def test_create(self):
        """
        Ensure Rune creation is successful.
        """
        rune_data = {'rank': 9, 'runeId': 5273}

        participant = self.match.participant_set.get(participant_id=1)

        self.assertTrue(participant.rune_set.all().exists())

        participant.rune_set.all().delete()

        self.assertFalse(participant.rune_set.all().exists())

        participant.rune_set.create_rune(rune_data)
        created = participant.rune_set.get(rank=9)

        self.assertEqual(created.rune_id, 5273)

